POST http://127.0.0.1:3000/users
content-type: application/json

{
    "id": 1,
    "name": "jone doe"
}

###

GET http://127.0.0.1:3000/users

### 

PUT http://127.0.0.1:3000/users/1
content-type: application/json

{
    "id": 1,
    "name": "jane doe"
}

###

DELETE http://127.0.0.1:3000/users/3

###

POST http://127.0.0.1:3000/notes
content-type: application/json

{
    "id": 1,
    "name": "aaa"
}

###

GET http://127.0.0.1:3000/notes

### 

PUT http://127.0.0.1:3000/notes/1
content-type: application/json

{
    "id": 1,
    "name": "aaa"
}

###

DELETE http://127.0.0.1:3000/notes/3